---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: httpd-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/httpd-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheshir-httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sheshir-httpd
  template:
    metadata:
      labels:
        app: sheshir-httpd
    spec:
      containers:
        - name: sheshir-httpd
          image: mahmudulhasansheshir/php-apache-mysql:v1.2
          volumeMounts:
            - name: httpd-persistent-storage
              mountPath: /var/www/html
          ports:
            - containerPort: 80
          # Other container specifications
      volumes:
        - name: httpd-persistent-storage
          persistentVolumeClaim:
            claimName: httpd-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: sheshir-httpd
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30090


